# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docs

# on:
#   push: 
#     branches: 
#       - master

on: push

jobs:
  build-and-install:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: check git log
      run: |
        git checkout setup-docs
        git --no-pager log -2
        

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install sphinx pydata-sphinx-theme
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install package
      run: |
        git --no-pager log -2
        python -m pip install --upgrade pip
        python -m pip install torch==1.7.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
        python -m pip install -e .

    - name: Make docs
      run: |
          cd docs
          make html
          git diff _build/html/FrEIA.html
